### ISSUE TITLE
Plugin does not install gradle compatible with ubuntu ARM64 (no gradle available)

### ISSUE THREAD

**Issue by danielporto** [rfrancis/asdf-gradle#8]
While compiling an ubuntu container in Mac M1, I've found the following problem:
There is no gradle version available for install using  asdf list all gradle.

Container base image: Ubuntu 20:04

uname -a
Linux cef6accac07d 5.10.25-linuxkit #1 SMP PREEMPT Tue Mar 23 09:24:45 UTC 2021 aarch64 aarch64 aarch64 GNU/Linux

Java asdf plugin installed with java -version
openjdk version "11.0.8" 2020-07-14 LTS
OpenJDK Runtime Environment Zulu11.41+75-CA (build 11.0.8+10-LTS)
OpenJDK 64-Bit Server VM Zulu11.41+75-CA (build 11.0.8+10-LTS, mixed mode)

**Comment by rfrancis** [comment]
The only reason I can think for that is something possibly being missing or incompatible with the commands used to get the list. Can you run this in the container and copy and paste the output?

`curl -s https://services.gradle.org/distributions/ | grep -e "distributions.*-bin.zip\"" | sed -e "s#^.*distributions/gradle-##" -e "s#-bin.zip.*##" | sort -t. -n | paste -s -d" " -`

**Comment by danielporto** [comment]
I've found this:
```
curl -s https://services.gradle.org/distributions/ | grep -e "distributions.*-bin.zip\"" | sed -e "s#^.*distributions/gradle-##" -e "s#-bin.zip.*##" | sort -t. -n | paste -s -d" " -

[1]    14443 segmentation fault  curl -s https://services.gradle.org/distributions/ |
       14444 exit 1              egrep -e "distributions.*-bin.zip\"" |
       14445 done                sed -e "s#^.*distributions/gradle-##" -e "s#-bin.zip.*##" |
       14446 done                sort -t. -n |
       14447 done                paste -s -d" " -
```
Curl is the culprit, not sure what's the solution though 

references also mentioned that here: https://stackoverflow.com/questions/68064909/curl-on-latest-ubuntu-and-debian-container-image-on-docker-desktop-3-4-0-on-mac
and here https://github.com/BloodHoundAD/BloodHound/issues/465

**Comment by rfrancis** [comment]
That's a poser all right. I see the issue affects wget as well, which suggests it's in a library really, but at any rate there goes my idea to try wget -O if curl fails... I fear this one may just have to remain unsolved until the curl (or libcurl, or whatever) problem is fixed..

**Comment by danielporto** [comment]
I've checked Ubuntu 21.04 has it fixed.
